-- ==========================================================================
-- SCRIPT COMPLETO DE CONFIGURAÇÃO DO SUPABASE (FECART)
-- Copie e cole todo este código no "SQL Editor" do seu painel Supabase.
-- ==========================================================================

-- 1. Criar Tabela de Usuários
CREATE TABLE IF NOT EXISTS public.users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username TEXT UNIQUE NOT NULL,
  password JSONB NOT NULL, -- Aceita texto simples ou lista de senhas (ex: admin)
  turma TEXT DEFAULT 'Geral',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 2. Criar Tabela de Agendamentos (com Horários, Token, Limite % e Auditoria)
CREATE TABLE IF NOT EXISTS public.appointments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  date_str TEXT UNIQUE NOT NULL, -- Garante EXATAMENTE 1 agendamento por dia no banco
  time_str TEXT DEFAULT '08:00' NOT NULL, -- Horário de início (ex: "14:00")
  duration_minutes INT DEFAULT 180 NOT NULL, -- Duração obrigatória de 3 horas (180 min)
  username TEXT NOT NULL,
  turma TEXT DEFAULT 'Geral',
  auth_token TEXT UNIQUE NOT NULL, -- Token de Segurança Criptográfico
  token_usage INT DEFAULT 1250 NOT NULL, -- Uso de Tokens de IA
  limit_percent INT DEFAULT 85 NOT NULL, -- Limite Restante em %
  device_info TEXT, -- Dados do navegador e dispositivo
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now()) NOT NULL
);

-- 3. Não há contas de demonstração neste arquivo. Crie usuários reais no
-- Supabase Auth e replique o perfil pelo comando `npm.cmd run users`.

-- 4. Habilitar Permissões de Leitura e Escrita Públicas (RLS)
ALTER TABLE public.users ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.appointments ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Permitir Leitura e Escrita em Users" ON public.users;
CREATE POLICY "Legacy users disabled" ON public.users FOR ALL TO authenticated USING (false) WITH CHECK (false);

DROP POLICY IF EXISTS "Permitir Leitura e Escrita em Appointments" ON public.appointments;
CREATE POLICY "Legacy appointments disabled" ON public.appointments FOR ALL TO authenticated USING (false) WITH CHECK (false);
